### ISSUE TITLE
Key Accessor function should have an index (incrementer) value as second argument

### ISSUE THREAD

**Issue by ekatzenstein** [react-tools/react-move#27]
I may be missing something, but it'd be very convenient to have an index value for the key accessor function.

**Comment by sghall** [comment]
Hey.  Good point.  I like this idea.  Just need to pass in "i" here...

https://github.com/react-tools/react-move/blob/master/src/NodeGroup/NodeGroup.js#L93

You want to do a PR?  Otherwise,  I'll add it in to the batch of updates I'm doing.

**Comment by ekatzenstein** [comment]
Here ya go: https://github.com/react-tools/react-move/pull/28

**Comment by sghall** [comment]
Released!
