### ISSUE TITLE
No typescript definitions for version 2

### ISSUE THREAD

**Issue by JamesMcMahon** [react-tools/react-move#29]
Typescript definitions were present for version 1 (as of https://github.com/react-tools/react-move/pull/8) but are now gone.

Originally called out in https://github.com/react-tools/react-move/issues/5. But I'd like to re-open for the new version.

**Comment by sghall** [comment]
Hey.  I don't use typescript but it would be nice to support it.  You want to do a PR for this?

**Comment by JamesMcMahon** [comment]
I don’t know when I will get around to it, but I’ll leave the issue open and someone else can pick it up if they beat me to it.

**Comment by sghall** [comment]
Released Typescript support in 2.4.0!  Let me know if there are any issues.

**Comment by kelly-tock** [comment]
seeing from the example code provided on the site TS issues with the jsx style attribute. had to break out the `any` escape hatch. any ideas?
