### ISSUE TITLE
TickGroup

### ISSUE THREAD

**Issue by ekatzenstein** [react-tools/react-move#30]
Why was TickGroup removed from Resonance for React-Move? Is there an alternative for setting up axes for data visualization?

**Comment by sghall** [comment]
Yeah,  good call.  We removed the TickGroup to keep the API for react-move very focused.  It's probably better to put it into your codebase (or offer it as a third-party component).  The react-move API is just Animate for single items and NodeGroup for an array of items. 

In earlier versions of resonance that component was much more valuable, but now it's really just a simple wrapper around NodeGroup so you can make axes by just implementing it in your code.

If you want to make animated axes you can just use the original resonance component as a blueprint. Checkout the resonance [TickGroup](https://github.com/sghall/resonance/blob/master/src/TickGroup/TickGroup.js) here.

Perhaps we should put an example in the docs with an animated axis and use that component (?)

**Comment by ekatzenstein** [comment]
Thanks @sghall. More examples would be great...would also help this awesome library to get more attention. I'm still on the search for a library that will replace d3's dom components (i.e.: d3.axis, as mentioned here: https://hackernoon.com/how-and-why-to-use-d3-with-react-d239eb1ea274) without having to create a faux dom, but am aware that's a tall order.

**Comment by techniq** [comment]
@ekatzenstein Take a look at https://github.com/hshoff/vx

**Comment by ekatzenstein** [comment]
Wow, hadn't seen this one. Thanks!

**Comment by techniq** [comment]
@ekatzenstein I've been kicking it around lately, along with react-move, and have had great success with them so far.  You can see using the 2 together from my collapsible tree example under the [in the wild](https://github.com/hshoff/vx#in-the-wild) section.  I've also seen [data-ui](https://github.com/williaster/data-ui) experimenting with the 2 as well.

**Comment by ekatzenstein** [comment]
Beautiful, that was my follow-up question: combining the two. Thanks @techniq
