### ISSUE TITLE
Support for flexDuration in v2?

### ISSUE THREAD

**Issue by chasedeanda** [react-tools/react-move#34]
### Problem or feature description
In v1 we could specify `flexDuration` so that if lots of animations were triggered at once, it would stagger them to prevent lag. Has this been removed in v2? I see the new timing object, but I'm wondering if there is an automatic way of handling rather than staggering them myself in the timing object.

### Versions (only needed for problems)

- React-Move: 2.6.0
- React: 16.0.0
- Browser: Chrome

**Comment by sghall** [comment]
Version 2.0 is a complete rewrite and there is no concept of `flexDuration` now.  Animations are managed by [d3-timer](https://github.com/d3/d3-timer) which has some really clever optimizations to handle thousands of concurrent interpolations efficiently.  I would try updating your animations without staggering them first.

**Comment by chasedeanda** [comment]
@sghall Thanks for the reply and great work on version 2 of this package, it's working really well and is a lot friendlier to use! 

I am updating in the ballpark of around 150 elements at the same time and it didn't perform well at all. The animations started to get very jumpy. I had to manually stagger different elements and that seemed to work okay. Is there anything you guys expose from d3-timer that I can use to try out different timings?

How was `flexDuration` handled in v1, and is it something that I can possibly handle in my app?

Thanks

**Comment by sghall** [comment]
Right on.  Thanks!

Hmmm, I would say you are not going to get 150 elements to animate smoothly in React.  It's just not going to do it...not with react-move or react-motion or any other lib.  There's just too much overhead with the VDOM stuff.  The timer will handle thousands of tweens but it has to call setState on each frame and React will just choke.

The React team toyed around with ideas to support animation for React 16, but looks like that got sidelined.  If you want to get into some of the details on this take a look at this thread...
https://github.com/facebook/react/issues/10703

Your idea of staggering is a good thought and I would look at strategies to group things together and animate the group.  That's a common strategy in SVG.  

Also, if you are not using the `NodeGroup` I would definitely use that component over the `Animate` component.  It's much more robust for handling lots of items.

If you want to setup a codesandbox to demonstrate what you need to do,  I can look at that.
