### ISSUE TITLE
<Animate /> state becomes out of sync with the show prop when it's toggled too quickly

### ISSUE THREAD

**Issue by denkristoffer** [react-tools/react-move#35]
### Problem
If you quickly toggle the `show` prop a few times, the `<Animate />` component becomes unable to render the state that it should. I'm guessing it happens if the previous transition hasn't been allowed to finish before toggling should start a new transition?

### Steps to reproduce
Click the button in this example to toggle state. At some point the black box should stop rendering when the button is active (blue):
https://codesandbox.io/s/6jqxjomm0r

- React-Move: 2.6.0
- React: 16.0.0
- Browser: Chrome

**Comment by sghall** [comment]
The update prop determines what will happen on an interrupt.  So in this case something like this...
https://codesandbox.io/s/8zvxqpl8p8

Try that out.

**Comment by denkristoffer** [comment]
Man, I've read the documentation site so many times and all these times I've just ignored `update` because I thought it was unnecessary for my use case! I apologise for the issue 😕 

And thanks for `react-move` it's a joy to work with!

**Comment by sghall** [comment]
No worries.  It's a little hard to grok, but it gives you some flexibility.

**Comment by LimeWub** [comment]
Hey there, sorry for necro-posting but I seem to be having this exact same "issue".

My code is something along these lines:

```
<Animate
    show={this.props.active} // boolean
    start={{
        opacity: 0
    }}
    enter={{
        opacity: [1],
        timing: {
            duration: 400,
            ease: easeCircleIn
        }
    }}
    leave={{
        opacity: [0],
        timing: {
            duration: 400,
            ease: easeCircleOut
    }}
/>
    {({ opacity }) => {
        return <div>Some stuff</div>
    }}
</Animate>
```

When I spam-click the button that passes through the `active` prop the Animation goes out of sync, ie. `active === true` but component not visible.
I see it was suggested to use the `update` prop on the component but I'm not sure how to do it.

The codesandbox link with the fix above is not accessible anymore so I can't check what solution had been provided :/
Can you please help me out with an example of what `update={}` should look like to handle animation interruptions?

Thank you :)
