### ISSUE TITLE
Tutorials?

### ISSUE THREAD

**Issue by loganpowell** [react-tools/react-move#36]
As [mentioned](https://medium.com/react-tools/react-move-2-0-resonance-joins-react-move-to-make-your-animations-even-better-2279d95cefaf) there are so many choices when trying to decide on an animation library to learn. You have a big advantage due to your merged forces and cross-platform appliance. I just wish there were more tutorials for how to use this. That's one of the key reasons there are so many libraries and the community is spread so thin... the lack of documentation. One knows not where to turn for a community that they feel will endure the evolutionary speed of the ecosystem and the lack of docs, tutorials, etc. is a big smell for the instability of a technology. I hope you guys will come forward to claim the prize. I'm rooting for you, but we need more cowbell! 

For real though, can a man get some tuts?

**Comment by sghall** [comment]
Yeah, docs are tough. I have been curious about how many people realize that you can click to reveal the code on all the examples(?)  You think that is obvious?  

Is that not, in your mind, an effective way to show people how to work with the library?  What do you think would make an effective tutorial?

Do you have any specific questions or can you point out something that you find difficult to understand?

**Comment by loganpowell** [comment]
Thank you for your response! Yes, I realized I could click to reveal the code for each example (thank you for that!), which I did, but I'm a complete beginner to animation and not familiar with D3 at all. 

Just speaking for myself: It would be nice to have a step-by-step example that lays out each of the features of React-Move so that you cover all your features just once (no less, no more), but so that a naive animator like myself can - with confidence feel like their use case is covered by your library (if possible at all).

Here's an example of a good tutorial for React-Motion:

https://medium.com/@nashvail/a-gentle-introduction-to-react-motion-dc50dd9f2459

He takes some time in educating the user on what each function is, which may seem a bit elementary, but I would argue that's what your audience needs. Don't be afraid to teach us like we're children :)

**Comment by loganpowell** [comment]
Sorry, I didn't fully address your response. As to:
>Do you have any specific questions or can you point out something that you find difficult to understand?
For now, I'm wondering if `react-move` will work with another library I'm working with `[react-snap](https://github.com/stereobooster/react-snap)` . It's a prerenderer that basically takes a snapshot - in a full browser - of each page (with a relative link) in your app. 

I've had some success using [ReactTransitionGroup and Animated](https://github.com/loganpowell/router-transition-animation) together. I would like to try React-Move too!

**Comment by jeremypeters** [comment]
@sghall FYI, personally I didn't realize that clicking the demo headers revealed the code - I couldn't understand why you would have demo but not display the code.
