### ISSUE TITLE
Requesting assistance on figuring out how to get grid animation working

### ISSUE THREAD

**Issue by amaidah** [react-tools/react-move#37]
### Problem or feature description
I am trying to get a basic grid animation working. I can't seem to figure it out, I've created a codesandbox with an example. 

I am looking to create a board with 'tiles' that animate from start to end location as the data-group changes, very similar to this example here: https://react-move.js.org/#/documentation/node-group

Please view the codesandbox here:
https://codesandbox.io/s/jn9yk73ok5

react-move: 2.6
react: 16
Bootstrap: 3.3.7

Any tips or assistance on how I would improve this is very much appreciated.

**Comment by sghall** [comment]
You could do this with react-move but you would have to calculate the layout for the grid items on each update.  Just swapping classes is not going to work.

You might want to look at:
https://github.com/STRML/react-grid-layout

**Comment by amaidah** [comment]
Hmm I see. Thanks for the quick reply.

Can you expand on what you mean by calculating the grid?

I will take a look at `react-grid` thanks.

**Comment by sghall** [comment]
You could use absolute positioning and calculate the new coordinates for each cell on each update and let react-move interpolate from the old layout to the new one. 

You can see how that works for an x, y coordinate in this example (second example on the NodeGroup docs page):
https://github.com/react-tools/react-move/blob/master/docs/src/routes/documentation/NodeGroup/Example2.js#L92

Uses the CSS translate prop:
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate
