### ISSUE TITLE
Any plans for migrate React deprecated lifecycle methods

### ISSUE THREAD

**Issue by markov00** [react-tools/react-move#43]
### Problem or feature description
I was just curious if you have any plans for migrate React 16.x  deprecated lifecycle methods?

I've seen that you are using `componentWillReceiveProps` in `Animate` and `NodeGroup`.

### Versions (only needed for problems)

- React-Move: 2.7.0

**Comment by vijayst** [comment]
@sghall I need this too. I can help in doing a PR if required. But it looks a bit difficult considering the use of setState in transitions. Thanks.

**Comment by sghall** [comment]
Yep.   Going to start working on this.

**Comment by sghall** [comment]
Ok.   Released in 2.9.0.  Try it out.  Let me know if there's any issues.

**Comment by sghall** [comment]
FYI. Had to push a 2.9.1 version with https://github.com/reactjs/react-lifecycles-compat to avoid breakage with older versions of react.  Bump to 3.0.0 if you're on 16.3.0 or later to get the version without the compat code in there.
