### ISSUE TITLE
Carousel example inside documentation

### ISSUE THREAD

**Issue by vctormb** [react-tools/react-move#44]
### Problem or feature description
I'm learning on how to use React-Move, but I'm facing some difficults, like creating a photo gallery carousel.

Is it possible to create an example, like in [React Motion Gallery](http://chenglou.github.io/react-motion/demos/demo4-photo-gallery/).

I think that this is a very useful example to demonstrate, sliding things from right to left, and vice-versa.

**Comment by sghall** [comment]
You absolutely could do this with react-move.   That demo is actually quite simple.  A total of ~80 lines.

https://github.com/chenglou/react-motion/blob/master/demos/demo4-photo-gallery/Demo.jsx

Anyone want to create a photo gallery demo?

**Comment by sghall** [comment]
Unfortunately, it does not look like we have any takers on this. We just don't have the bandwidth to produce anymore demos.
