### ISSUE TITLE
Disable Animations

### ISSUE THREAD

**Issue by amcdnl** [react-tools/react-move#45]
## Feature Request
I would like the ability to conditionally disable animations.

### Scenario
Run the animation on initial render and updates but then when a user is interacting w/ the chart, say via panning/zooming turn off animations for those updates. Right now I have a flag that will turn off duration/etc when that is happening but due to the queue system under the hood it lags a bit.

```
  getEnterUpdate(data: DataShape, index: number) {
    return {
      opacity: [1],
      cx: [this.props.xScale(data.x)],
      cy: [this.props.yScale(data.y)],
      timing: this.props.animated
        ? { duration: 300, delay: index * 10, ease: easeExpInOut }
        : { duration: 0 }
    };
  }
```

Any suggestions @sghall ?

**Comment by sghall** [comment]
In React 16.8 you can call `componentWillDoWhatIWant`:

```
componentWillDoWhatIWant() {
   return true
}
```

That will run a neural net on your FB photos and figure what you're trying to do. Much easier than mucking around with props and state.  

LOL.  Just noticed this was from you @amcdnl.  Blowing the dust off this library.

In case anyone still needs the answer... if memory serves...if you just return the value (not in an array) it will set it immediately ignoring all the timing stuff. Never really tried it for something like this but my guess is:
```
getEnterUpdate(data: DataShape, index: number) {
   const { xScale, yScale, animated } = this.props

    return {
      opacity:  animated ? [1] : 1,
      cx: animated ? [xScale(data.x)]: xScale(data.x) ,
      cy: animated ? [yScale(data.y)]: yScale(data.y),
      timing: { duration: 300, delay: index * 10, ease: easeExpInOut }
   }
}
```

**Comment by amcdnl** [comment]
@sghall - Haha yup - long time!

Thanks for the follow up!
