### ISSUE TITLE
Problems with data display when using Animate

### ISSUE THREAD

**Issue by vijayst** [react-tools/react-move#46]
### Problem or feature description
I am using Animate to show a hover state. I am passing in the data as one of the state param in the start prop. I update the data in the update prop after a delay. But the data that I am passing in via the update prop seems to translate the underlying data. For example, the text "White" appears as rgb(255, 255, 255).

### Steps to reproduce (only needed for problems)
The code for the Animate is shown below. Passing in the data as one of the state param is causing the issue.
```
<Animate
    show={show}
    start={{
        opacity: 0,
        data
    }}
    enter={[
        {
            opacity: [1],
            timing: {
                duration: Animation.PrimaryDuration,
                ease: easeQuadInOut
            }
        }
    ]}
    update={[
        {
            opacity: [0],
            timing: {
                duration: Animation.PrimaryDuration,
                ease: easeQuadInOut
            }
        },
        {
            opacity: [1],
            timing: {
                duration: Animation.PrimaryDuration,
                delay: Animation.PrimaryDuration,
                ease: easeQuadInOut
            }
        },
        {
            data: [data],
            timing: {
                duration: 0,
                delay: Animation.PrimaryDuration
            }
        }
    ]}
    leave={[
        {
            opacity: [0],
            timing: {
                duration: Animation.PrimaryDuration,
                ease: easeQuadInOut
            }
        }
    ]}
>
    {({ opacity, data }) => (
        <div
            ref={this.comp}
            className="hover-state"
            style={{ left: x, top: y, opacity }}
        >
            {data.map(d => (
                <div key={d.name} className="hover-state__item">
                    <div>{d.name}:</div>
                    <div>{d.value}</div>
                </div>
            ))}
        </div>
    )}
</Animate>
```
Hover over White using enter transition:
![screenshot 2018-12-06 at 2 29 46 pm](https://user-images.githubusercontent.com/3457565/49573541-3a99bd80-f964-11e8-8f5d-590c51df3ae7.png)

Hover over White using update transition:
![screenshot 2018-12-06 at 2 29 57 pm](https://user-images.githubusercontent.com/3457565/49573555-42f1f880-f964-11e8-8c0f-8f7dc8c62069.png)

### Versions (only needed for problems)

- React-Move: 2.8.0
- React: 16.5
- Browser: Chrome

**Comment by sghall** [comment]
Hey there.  Hmmm...I'm a little unclear on what the effect should be.  It's interpolating your data object, which is not what you want.  Can you put this in a CodeSandbox?  Be glad to take a look.

**Comment by vijayst** [comment]
Thanks, Here is the [CodeSandbox](https://codesandbox.io/s/lx38nknj1z).

**Comment by sghall** [comment]
How about something like this?
https://codesandbox.io/s/n60kqpq3m

**Comment by vijayst** [comment]
Thanks @sghall . The limitation with the approach is that it does not animate from 1 to 0 while doing an update. Increased the animation duration to make it clearly visible - https://codesandbox.io/s/3yqwxvmv5m

I worked around this problem in another example by using NodeGroup instead of Animate.

**Comment by sghall** [comment]
Ahh,  I see.  Right, if you use NodeGroup then it's just one element leaving and one entering, so you could get that effect.

**Comment by vijayst** [comment]
I think Animate needs to capture data in a prop. 

Let's say show=false and data becomes empty in the same step, the leave animation collapses immediately because of no data.

If I capture data in the initial state, then the update animation does not have the new data reflected as it is captured only in start.

If I add data to the state in update prop, Animate tries to do something with that data causing this error.

**Comment by sghall** [comment]
Hey, this component just got an overhaul in 2.9.0 that was just released.  Try it out again and let me know if you still have issues.
