### ISSUE TITLE
package-lock.json seems to be incorrect

### ISSUE THREAD

**Issue by vijayst** [react-tools/react-move#49]
### Problem or feature description
package-lock.json seems to be incorrect
See the error screenshot

### Steps to reproduce (only needed for problems)
nvm use 8
npm i

### Versions (only needed for problems)
latest source code

![screenshot 2019-01-11 at 10 20 52 am](https://user-images.githubusercontent.com/3457565/51013835-b356ef80-158a-11e9-9bde-efea15e32764.png)

**Comment by vijayst** [comment]
Also, when I run `npm test`, I get this error:
![screenshot 2019-01-11 at 11 06 52 am](https://user-images.githubusercontent.com/3457565/51015176-2e230900-1591-11e9-9f13-dae1ad2ab6dc.png)

Will be happy to contribute to this repo if I get past the initial setup. Thanks.

**Comment by sghall** [comment]
Ok.  Yep, all the dev deps need to be updated.  I'm going to start working on this.  Thanks.
